package com.apabi.r2k.test.model;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user.id
     *
     * @mbggenerated Fri Mar 21 17:37:42 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user.name
     *
     * @mbggenerated Fri Mar 21 17:37:42 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user.age
     *
     * @mbggenerated Fri Mar 21 17:37:42 CST 2014
     */
    private String age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user.id
     *
     * @return the value of test_user.id
     *
     * @mbggenerated Fri Mar 21 17:37:42 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user.id
     *
     * @param id the value for test_user.id
     *
     * @mbggenerated Fri Mar 21 17:37:42 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user.name
     *
     * @return the value of test_user.name
     *
     * @mbggenerated Fri Mar 21 17:37:42 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user.name
     *
     * @param name the value for test_user.name
     *
     * @mbggenerated Fri Mar 21 17:37:42 CST 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user.age
     *
     * @return the value of test_user.age
     *
     * @mbggenerated Fri Mar 21 17:37:42 CST 2014
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user.age
     *
     * @param age the value for test_user.age
     *
     * @mbggenerated Fri Mar 21 17:37:42 CST 2014
     */
    public void setAge(String age) {
        this.age = age;
    }
}